name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t my-app-image .

    - name: Push Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        docker tag my-app-image cdineshreddy13446/my-app-image:latest
        docker push cdineshreddy13446/my-app-image:latest

    - name: Install OpenShift CLI
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar -xvf openshift-client-linux.tar.gz
        sudo mv oc /usr/local/bin/
        sudo mv kubectl /usr/local/bin/

    - name: Deploy to OpenShift
      env:
        OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      run: |
        # Log in to OpenShift
        oc login --token=$OPENSHIFT_TOKEN --server=$OPENSHIFT_SERVER
    
        # Switch to the existing project
        oc project dineshreddy13446-dev
    
        # Deploy the DockerHub image
        oc new-app docker.io/cdineshreddy13446/my-app-image:latest --name=my-app
    
        # Expose the application to create a public route
        oc expose svc/my-app

